services:
  navigatr:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./public/configuration/config.json:/usr/share/nginx/html/configuration/config.json:ro
      - ./public/configuration/apps.json:/usr/share/nginx/html/configuration/apps.json:ro
